version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - 5173:5173
  backend:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server/db:/data
  load-balancer:
    build: ./server
    ports:
      - 4000:4000
    command: node loadbalancer.js
